<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Vitamin C Plus',
                'slug' => 'vitamin-c-plus',
                'sku' => 'PRO-VC-001',
                'category' => 'Supplements',
                'image' => 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80',
                'description' => 'A premium immune-support formula with vitamin C, zinc, and elderberry for everyday wellbeing.',
                'short_description' => 'Daily immune support',
                'price' => 29.99,
                'compare_price' => 39.99,
                'stock' => 36,
                'status' => 'published',
                'featured' => true,
            ],
            [
                'name' => 'Modafinil 200mg',
                'slug' => 'modafinil-200mg',
                'sku' => 'PHA-MOD-200',
                'category' => 'Focus & Energy',
                'image' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80',
                'description' => 'High-potency wakefulness support in 10 tablets for improved focus and daily alertness.',
                'short_description' => '10 tablets · 200mg',
                'price' => 70.00,
                'compare_price' => 95.00,
                'stock' => 25,
                'status' => 'published',
                'featured' => true,
            ],
            [
                'name' => 'Xanax Upjohn 2mg',
                'slug' => 'xanax-upjohn-2mg',
                'sku' => 'PHA-XAN-2',
                'category' => 'Anxiety Relief',
                'image' => 'https://images.unsplash.com/photo-1550572017-7aee4d5f6d0c?auto=format&fit=crop&w=900&q=80',
                'description' => 'Clinically trusted anxiety relief in a 30-tablet pack for stress and panic support.',
                'short_description' => '30 tablets · 2mg',
                'price' => 280.00,
                'compare_price' => 340.00,
                'stock' => 12,
                'status' => 'published',
                'featured' => true,
            ],
            [
                'name' => 'Xanax Pfizer 2mg',
                'slug' => 'xanax-pfizer-2mg',
                'sku' => 'PHA-XAN-PF',
                'category' => 'Anxiety Relief',
                'image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=900&q=80',
                'description' => 'Premium 50-tablet supply designed for ongoing anxiety management and symptom control.',
                'short_description' => '50 tablets · 2mg',
                'price' => 350.00,
                'compare_price' => 420.00,
                'stock' => 10,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Ksalol 1mg',
                'slug' => 'ksalol-1mg',
                'sku' => 'PHA-KSA-1',
                'category' => 'Anxiety Relief',
                'image' => 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=900&q=80',
                'description' => 'Alprazolam equivalent for discreet support with a 30-tablet pack for everyday use.',
                'short_description' => '30 tablets · 1mg',
                'price' => 100.00,
                'compare_price' => 130.00,
                'stock' => 18,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Bensedin 10mg',
                'slug' => 'bensedin-10mg',
                'sku' => 'PHA-BEN-10',
                'category' => 'Sleep Support',
                'image' => 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80',
                'description' => 'Diazepam equivalent designed to support sleep quality and relaxation in a trusted 30-tablet format.',
                'short_description' => '30 tablets · 10mg',
                'price' => 100.00,
                'compare_price' => 120.00,
                'stock' => 22,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Rivotril 2mg',
                'slug' => 'rivotril-2mg',
                'sku' => 'PHA-RIV-2',
                'category' => 'Sleep Support',
                'image' => 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=900&q=80',
                'description' => 'Clonazepam support in a 30-tablet pack for well-rested nights and calmer routines.',
                'short_description' => '30 tablets · 2mg',
                'price' => 100.00,
                'compare_price' => 125.00,
                'stock' => 15,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Belbien 10mg',
                'slug' => 'belbien-10mg',
                'sku' => 'PHA-BEL-10',
                'category' => 'Sleep Support',
                'image' => 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?auto=format&fit=crop&w=900&q=80',
                'description' => 'Zolpidem-based support for deeper, more restful sleep and improved night-time recovery.',
                'short_description' => '20 tablets · 10mg',
                'price' => 100.00,
                'compare_price' => 135.00,
                'stock' => 17,
                'status' => 'published',
                'featured' => true,
            ],
            [
                'name' => 'Tramal 100mg',
                'slug' => 'tramal-100mg',
                'sku' => 'PHA-TRA-100',
                'category' => 'Pain Relief',
                'image' => 'https://images.unsplash.com/photo-1607619056574-7b8d0c7b7e6c?auto=format&fit=crop&w=900&q=80',
                'description' => 'Effective pain management support with 50 tablets in a dependable, high-strength format.',
                'short_description' => '50 tablets · 100mg',
                'price' => 140.00,
                'compare_price' => 180.00,
                'stock' => 30,
                'status' => 'published',
                'featured' => true,
            ],
            [
                'name' => 'Tramal 200mg',
                'slug' => 'tramal-200mg',
                'sku' => 'PHA-TRA-200',
                'category' => 'Pain Relief',
                'image' => 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80',
                'description' => 'Strong pain relief option for more intense discomfort with a 50-tablet pack.',
                'short_description' => '50 tablets · 200mg',
                'price' => 200.00,
                'compare_price' => 250.00,
                'stock' => 20,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Oxycontin 40mg',
                'slug' => 'oxycontin-40mg',
                'sku' => 'PHA-OXY-40',
                'category' => 'Pain Relief',
                'image' => 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=900&q=80',
                'description' => 'Prescription pain relief in a 10-tablet format for sustained comfort and symptom control.',
                'short_description' => '10 tablets · 40mg',
                'price' => 200.00,
                'compare_price' => 240.00,
                'stock' => 8,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Pregabalin 300mg',
                'slug' => 'pregabalin-300mg',
                'sku' => 'PHA-PREG-300',
                'category' => 'Neurological Care',
                'image' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=900&q=80',
                'description' => 'Nerve support treatment in a 30-tablet pack for daily comfort and recovery routines.',
                'short_description' => '30 tablets · 300mg',
                'price' => 100.00,
                'compare_price' => 130.00,
                'stock' => 26,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Concerta 36mg',
                'slug' => 'concerta-36mg',
                'sku' => 'PHA-CON-36',
                'category' => 'ADHD Support',
                'image' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=80',
                'description' => 'Concentrated support for focus and daily attention in a trusted 10-tablet format.',
                'short_description' => '10 tablets · 36mg',
                'price' => 200.00,
                'compare_price' => 250.00,
                'stock' => 14,
                'status' => 'published',
                'featured' => true,
            ],
            [
                'name' => 'Adipex 75mg',
                'slug' => 'adipex-75mg',
                'sku' => 'PHA-ADI-75',
                'category' => 'Weight Management',
                'image' => 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80',
                'description' => 'A weight management support formula designed for targeted appetite control and routine consistency.',
                'short_description' => '30 tablets · 75mg',
                'price' => 190.00,
                'compare_price' => 240.00,
                'stock' => 18,
                'status' => 'published',
                'featured' => false,
            ],
            [
                'name' => 'Ozempic (Semaglutide)',
                'slug' => 'ozempic-semaglutide',
                'sku' => 'PHA-OZE-2',
                'category' => 'Weight Management',
                'image' => 'https://images.unsplash.com/photo-1535914254981-b5012e51d1b7?auto=format&fit=crop&w=900&q=80',
                'description' => 'Advanced semaglutide support for modern weight management programs with a discreet delivery option.',
                'short_description' => '2mg supply',
                'price' => 450.00,
                'compare_price' => 520.00,
                'stock' => 7,
                'status' => 'published',
                'featured' => true,
            ],
        ];

        foreach ($products as $item) {
            $imageUrl = $item['image'];
            unset($item['image']);

            $product = Product::updateOrCreate(['sku' => $item['sku']], $item);

            $product->images()->firstOrCreate(['sort_order' => 0], ['url' => $imageUrl]);
        }
    }
}
